### ISSUE TITLE
Can't set Filesystem to HostFS

### ISSUE THREAD

**Issue by TimPL** [Septercius/rpcemu-dev#2] opened 2020-04-24 12:51 UTC
When I enter <configure filesystem hostfs>, I get the response <filing system hostfs not present <Error number &F8>>.
I observe that there is no <hostfs> directory inside the Data directory.  I tried adding one but this made no difference.  HostFS is to be found within the Data > riscos-progs directory.
<configure boot> and <desktop> commands work OK. 
What else should I have done?

**Comment by Septercius** [comment] 2020-04-24 13:32
This is being caused by the "poduleroms" being missing (something that my build/package script missed).

**Comment by Septercius** [comment] 2020-04-24 16:55
There is a new version of the 0.9.2a release that includes a fix for this.  It now includes the missing "poduleroms" folder and leaves out the unnecessary "riscos-progs" folder.

**Comment by TimPL** [comment] 2020-04-24 17:00
Dear Tim,

Many thanks.  I shall get down to work very shortly.  Interesting to know that riscos-progs is not needed, perhaps it is a bit of disc space to save on my other emulators.

regards,

Tim

-- 
Tim Powys-Lybbe                                                           tim@powys.org
                        for a miscellany of bygones: http://powys.org/

**Comment by TimPL** [comment] 2020-04-24 18:04
Dear Tim,

One last problem, there was no hostfs directory inside Data.  I retried my guess of the last time that it needed this directory so did that, bunged in the HardDisc self extracting file and was able to start up successfully.

I then copied across everything from my other RPCEmu and all worked.  In particular the networking works, which is the primary objective for me to upgrade to this.

Many thanks,

Tim

-- 
Tim Powys-Lybbe                                                           tim@powys.org
                        for a miscellany of bygones: http://powys.org/

> Begin forwarded message:
> 
> From: Tim Powys-Lybbe <tim@powys.org>
> Subject: Re: [Septercius/rpcemu-dev] Can't set Filesystem to HostFS (#2)
> Date: 24 April 2020 at 6:00:39 pm BST
> To: Septercius/rpcemu-dev <reply@reply.github.com>
> 
> Dear Tim,
> 
> Many thanks.  I shall get down to work very shortly.  Interesting to know that riscos-progs is not needed, perhaps it is a bit of disc space to save on my other emulators.
> 
> regards,
> 
> Tim
> 
> -- 
> Tim Powys-Lybbe                                                           tim@powys.org
>                        for a miscellany of bygones: http://powys.org/
>

**Comment by Septercius** [comment] 2020-05-08 13:42
The new 0.9.3a release now includes the missing "hostfs" folder.  Glad to see everything is working, and thank you for the bug report and the feedback.

**Comment by TimPL** [comment] 2020-05-11 18:49
Dear Tim

I have just read and understood about the release of the new 0.9.3 master version and that you have come up trumps within 24 hours.  I have tested this, on only one machine so far, and it works perfectly.  I am not clear about the completely-all-in-one Mac version and whether there is something that we just download and it all works, but until that arrives I am making a written procedure to start from the current Mac offering and to get that to a working system on a Mac.  I’ll pass a copy on when I’ve tested it on another machine.

Many thanks for the latest version.

regards,

Tim
 
-- 
Tim Powys-Lybbe                                                           tim@powys.org
                        for a miscellany of bygones: http://powys.org/

**Closed as completed** 2020-06-29 16:38 UTC
